site_name: Circle Of Fifths
site_url: https://ronligt.github.io/circle_of_fifths/

repo_url: https://github.com/ronligt/circle_of_fifths

theme:
  name: 'material'

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - attr_list
  - md_in_html

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js