name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Compile base.pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: circle_of_fifths.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=output -jobname=base
          pre_compile: "export BASE=1"
      - name: Compile degree.pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: circle_of_fifths.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=output -jobname=degree
          pre_compile: "export DEGREE=1"
      - name: Compile chord.pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: circle_of_fifths.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=output -jobname=chord
          pre_compile: "export CHORD=1"
      - name: Compile example.pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: circle_of_fifths.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=output -jobname=example
          pre_compile: "export EXAMPLE=1"
      - name: Compile description.pdf
        uses: xu-cheng/latex-action@v2
        with:
          root_file: circle_of_fifths.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=output -jobname=description
          pre_compile: "export COLOR=1"
      - name: Convert example
        uses: jruipinto/ImageMagick-action@v1
        with:
          command: convert -density 150 -output/example.pdf output/example.png
      - name: Convert example
        uses: jruipinto/ImageMagick-action@v1
        with:
          command: convert -crop 60%x60%x+0+0 -gravity northeast -density 150 output/description.pdf output/description.png
      - name: Upload PDF and PNG
        uses: actions/upload-artifact@v2
        with:
          name: output
          path: |
            output/base.pdf
            output/degree.pdf
            output/chord.pdf
            output/example.png
            output/description.png
