name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: circle_of_fifths.tex
          args: -pdf -file-line-error -halt-on-error -interaction=nonstopmode -outdir=PDFs
          pre_compile: "export BASE=1"
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: PDFs/circle_of_fifths.pdf
